version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    groups:
      backend-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      frontend-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
    groups:
      docs-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/test"
    schedule:
      interval: "weekly"
    groups:
      test-deps:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    groups:
      docker-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-deps:
        patterns:
          - "*"
